function y = RatDataMatlabBPFilter(x)
%RATDATAMATLABBPFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 22-Jul-2015 12:28:13

persistent Hd;

if isempty(Hd)
    
    Fstop1 = 100;         % First Stopband Frequency
    Fpass1 = 300;         % First Passband Frequency
    Fpass2 = 6000;        % Second Passband Frequency
    Fstop2 = 9000;        % Second Stopband Frequency
    Astop1 = 60;          % First Stopband Attenuation (dB)
    Apass  = 1;           % Passband Ripple (dB)
    Astop2 = 60;          % Second Stopband Attenuation (dB)
    Fs     = 24414.0625;  % Sampling Frequency
    
    h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
        Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


